<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FeedComponent;

class FeedComponentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * This seeder creates comprehensive feed components with realistic
     * nutritional values based on actual poultry feed ingredient data.
     */
    public function run(): void
    {
        $components = [
            // ========== ENERGY SOURCES (GRAINS) ==========
            [
                'name' => 'Maize (Yellow Corn)',
                'description' => 'High-energy grain, primary energy source in poultry feeds. Rich in carbohydrates and low in fiber. Excellent palatability and digestibility.',
                'unit' => 'kg',
                'crude_protein' => 8.5,
                'crude_fat' => 3.5,
                'crude_fiber' => 2.2,
                'calcium' => 0.03,
                'phosphorus' => 0.28,
                'metabolizable_energy' => 3350,
                'moisture' => 12.0,
                'ash' => 1.4,
                'status' => 'active',
            ],
            [
                'name' => 'White Maize',
                'description' => 'White variety of maize, similar nutritional profile to yellow maize. Preferred in some regions for feed production. High-energy grain with excellent digestibility.',
                'unit' => 'kg',
                'crude_protein' => 8.3,
                'crude_fat' => 3.3,
                'crude_fiber' => 2.3,
                'calcium' => 0.03,
                'phosphorus' => 0.27,
                'metabolizable_energy' => 3340,
                'moisture' => 12.0,
                'ash' => 1.4,
                'status' => 'active',
            ],
            [
                'name' => 'Wheat',
                'description' => 'Alternative energy source to maize. Contains more protein than maize but may have anti-nutritional factors. Good for layer feeds.',
                'unit' => 'kg',
                'crude_protein' => 12.0,
                'crude_fat' => 1.8,
                'crude_fiber' => 2.5,
                'calcium' => 0.05,
                'phosphorus' => 0.35,
                'metabolizable_energy' => 3150,
                'moisture' => 12.0,
                'ash' => 1.7,
                'status' => 'active',
            ],
            [
                'name' => 'Sorghum (Millet)',
                'description' => 'Drought-resistant grain, good alternative to maize. Lower energy than maize but suitable for tropical climates. May contain tannins.',
                'unit' => 'kg',
                'crude_protein' => 9.0,
                'crude_fat' => 3.0,
                'crude_fiber' => 2.7,
                'calcium' => 0.04,
                'phosphorus' => 0.30,
                'metabolizable_energy' => 3200,
                'moisture' => 12.0,
                'ash' => 1.5,
                'status' => 'active',
            ],
            [
                'name' => 'Rice Bran',
                'description' => 'By-product of rice milling. High in fat and fiber. Good source of B-vitamins. Can be used up to 10-15% in poultry feeds.',
                'unit' => 'kg',
                'crude_protein' => 12.5,
                'crude_fat' => 15.0,
                'crude_fiber' => 11.0,
                'calcium' => 0.08,
                'phosphorus' => 1.50,
                'metabolizable_energy' => 2800,
                'moisture' => 11.0,
                'ash' => 8.5,
                'status' => 'active',
            ],
            [
                'name' => 'Wheat Bran',
                'description' => 'High-fiber by-product of wheat milling. Good source of B-vitamins and minerals. Use in moderation due to high fiber content.',
                'unit' => 'kg',
                'crude_protein' => 15.5,
                'crude_fat' => 4.0,
                'crude_fiber' => 9.5,
                'calcium' => 0.12,
                'phosphorus' => 1.20,
                'metabolizable_energy' => 1800,
                'moisture' => 12.0,
                'ash' => 5.5,
                'status' => 'active',
            ],
            [
                'name' => 'Cassava Meal',
                'description' => 'Dried cassava root meal. High in energy but low in protein. Must be properly processed to remove cyanide. Good for energy supplementation.',
                'unit' => 'kg',
                'crude_protein' => 2.5,
                'crude_fat' => 0.5,
                'crude_fiber' => 3.5,
                'calcium' => 0.20,
                'phosphorus' => 0.10,
                'metabolizable_energy' => 3100,
                'moisture' => 12.0,
                'ash' => 2.0,
                'status' => 'active',
            ],

            // ========== PROTEIN SOURCES (OILSEEDS & MEALS) ==========
            [
                'name' => 'Full Fat Soya (Full-Fat Soybean)',
                'description' => 'Whole soybeans with oil intact, not processed to extract oil. Higher energy and fat content than soybean meal. Excellent protein source with good amino acid profile. Must be properly heat-treated to destroy anti-nutritional factors.',
                'unit' => 'kg',
                'crude_protein' => 38.0,
                'crude_fat' => 18.0,
                'crude_fiber' => 5.0,
                'calcium' => 0.25,
                'phosphorus' => 0.60,
                'metabolizable_energy' => 3600,
                'moisture' => 10.0,
                'ash' => 4.5,
                'status' => 'active',
            ],
            [
                'name' => 'Soybean Meal (48% CP)',
                'description' => 'Premium protein source, most commonly used in poultry feeds. High-quality amino acid profile, especially lysine. Well-balanced for all poultry types.',
                'unit' => 'kg',
                'crude_protein' => 48.0,
                'crude_fat' => 1.5,
                'crude_fiber' => 3.5,
                'calcium' => 0.30,
                'phosphorus' => 0.65,
                'metabolizable_energy' => 2400,
                'moisture' => 12.0,
                'ash' => 6.5,
                'status' => 'active',
            ],
            [
                'name' => 'Soybean Meal (44% CP)',
                'description' => 'Standard soybean meal with slightly lower protein content. More economical option while still providing excellent amino acid profile.',
                'unit' => 'kg',
                'crude_protein' => 44.0,
                'crude_fat' => 1.8,
                'crude_fiber' => 4.0,
                'calcium' => 0.28,
                'phosphorus' => 0.60,
                'metabolizable_energy' => 2350,
                'moisture' => 12.0,
                'ash' => 6.8,
                'status' => 'active',
            ],
            [
                'name' => 'Groundnut Cake (Peanut Meal)',
                'description' => 'High-protein meal from groundnut processing. Good alternative to soybean meal. Rich in arginine but lower in lysine. Watch for aflatoxin contamination.',
                'unit' => 'kg',
                'crude_protein' => 45.0,
                'crude_fat' => 6.0,
                'crude_fiber' => 5.5,
                'calcium' => 0.15,
                'phosphorus' => 0.55,
                'metabolizable_energy' => 2600,
                'moisture' => 10.0,
                'ash' => 5.0,
                'status' => 'active',
            ],
            [
                'name' => 'Sunflower Meal',
                'description' => 'By-product of sunflower oil extraction. Good protein source but high in fiber. Lower energy than soybean meal. Suitable for layer feeds.',
                'unit' => 'kg',
                'crude_protein' => 35.0,
                'crude_fat' => 2.0,
                'crude_fiber' => 25.0,
                'calcium' => 0.40,
                'phosphorus' => 1.00,
                'metabolizable_energy' => 1800,
                'moisture' => 10.0,
                'ash' => 6.5,
                'status' => 'active',
            ],
            [
                'name' => 'Cottonseed Meal',
                'description' => 'Protein source from cotton processing. Contains gossypol which can be toxic. Must be used in limited quantities (max 5-10%). Higher in fiber.',
                'unit' => 'kg',
                'crude_protein' => 41.0,
                'crude_fat' => 1.5,
                'crude_fiber' => 12.0,
                'calcium' => 0.20,
                'phosphorus' => 1.10,
                'metabolizable_energy' => 2000,
                'moisture' => 10.0,
                'ash' => 6.0,
                'status' => 'active',
            ],
            [
                'name' => 'Palm Kernel Cake',
                'description' => 'By-product of palm oil extraction. High in fiber, moderate protein. Lower energy and palatability. Use in limited amounts (max 10-15%).',
                'unit' => 'kg',
                'crude_protein' => 16.0,
                'crude_fat' => 8.0,
                'crude_fiber' => 20.0,
                'calcium' => 0.25,
                'phosphorus' => 0.60,
                'metabolizable_energy' => 2000,
                'moisture' => 11.0,
                'ash' => 4.5,
                'status' => 'active',
            ],
            [
                'name' => 'Sesame Meal',
                'description' => 'High-protein meal from sesame processing. Good amino acid profile but lower in lysine than soybean. Can replace part of soybean meal.',
                'unit' => 'kg',
                'crude_protein' => 42.0,
                'crude_fat' => 10.0,
                'crude_fiber' => 6.5,
                'calcium' => 2.20,
                'phosphorus' => 1.20,
                'metabolizable_energy' => 2500,
                'moisture' => 10.0,
                'ash' => 10.5,
                'status' => 'active',
            ],

            // ========== ANIMAL PROTEIN SOURCES ==========
            [
                'name' => 'Fish Meal (65% CP)',
                'description' => 'Premium animal protein source. Excellent amino acid profile, especially methionine and lysine. High in calcium and phosphorus. Best quality for starter feeds.',
                'unit' => 'kg',
                'crude_protein' => 65.0,
                'crude_fat' => 8.0,
                'crude_fiber' => 0.5,
                'calcium' => 5.50,
                'phosphorus' => 3.20,
                'metabolizable_energy' => 3000,
                'moisture' => 10.0,
                'ash' => 18.0,
                'status' => 'active',
            ],
            [
                'name' => 'Fish Meal (55% CP)',
                'description' => 'Standard fish meal with good protein content. More economical than premium grade. Still provides excellent amino acids and minerals.',
                'unit' => 'kg',
                'crude_protein' => 55.0,
                'crude_fat' => 10.0,
                'crude_fiber' => 0.5,
                'calcium' => 6.00,
                'phosphorus' => 3.50,
                'metabolizable_energy' => 2800,
                'moisture' => 10.0,
                'ash' => 20.0,
                'status' => 'active',
            ],
            [
                'name' => 'Meat and Bone Meal',
                'description' => 'Rendered animal by-products. Good source of protein, calcium, and phosphorus. Must be properly processed to ensure safety. Use in moderation.',
                'unit' => 'kg',
                'crude_protein' => 50.0,
                'crude_fat' => 8.0,
                'crude_fiber' => 2.0,
                'calcium' => 10.0,
                'phosphorus' => 5.0,
                'metabolizable_energy' => 2400,
                'moisture' => 8.0,
                'ash' => 30.0,
                'status' => 'active',
            ],
            [
                'name' => 'Blood Meal',
                'description' => 'Dried blood from slaughterhouses. Very high in protein and lysine but low in other amino acids. Use in limited amounts (max 2-3%).',
                'unit' => 'kg',
                'crude_protein' => 85.0,
                'crude_fat' => 1.0,
                'crude_fiber' => 1.0,
                'calcium' => 0.30,
                'phosphorus' => 0.25,
                'metabolizable_energy' => 2800,
                'moisture' => 10.0,
                'ash' => 4.0,
                'status' => 'active',
            ],

            // ========== MINERAL SOURCES ==========
            [
                'name' => 'Limestone (Calcium Carbonate)',
                'description' => 'Primary calcium source for poultry feeds. Essential for bone formation and eggshell quality. Use fine-ground for better absorption.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 38.0,
                'phosphorus' => 0.02,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 98.0,
                'status' => 'active',
            ],
            [
                'name' => 'Dicalcium Phosphate (DCP)',
                'description' => 'Source of both calcium and phosphorus. Highly bioavailable. Essential for bone development and metabolic functions. Standard mineral supplement.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 23.0,
                'phosphorus' => 18.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 95.0,
                'status' => 'active',
            ],
            [
                'name' => 'Monocalcium Phosphate (MCP)',
                'description' => 'Highly bioavailable source of calcium and phosphorus. More soluble than DCP. Premium mineral supplement for optimal bone health.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 16.0,
                'phosphorus' => 21.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 96.0,
                'status' => 'active',
            ],
            [
                'name' => 'Oyster Shell',
                'description' => 'Natural source of calcium carbonate. Large particle size provides slow-release calcium for layers. Excellent for eggshell quality.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 38.5,
                'phosphorus' => 0.10,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 98.5,
                'status' => 'active',
            ],
            [
                'name' => 'Salt (Sodium Chloride)',
                'description' => 'Essential for maintaining electrolyte balance and feed palatability. Required in all poultry feeds. Use iodized salt for additional benefits.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 0.5,
                'ash' => 99.5,
                'status' => 'active',
            ],
            [
                'name' => 'Tricalcium Phosphate',
                'description' => 'Source of calcium and phosphorus with good bioavailability. Alternative to DCP and MCP. Provides both essential minerals in balanced ratio.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 34.0,
                'phosphorus' => 18.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 96.0,
                'status' => 'active',
            ],
            [
                'name' => 'Bone Meal',
                'description' => 'Ground animal bones. Natural source of calcium and phosphorus. Good bioavailability. Also contains trace minerals. Must be properly processed.',
                'unit' => 'kg',
                'crude_protein' => 5.0,
                'crude_fat' => 3.0,
                'crude_fiber' => 0.0,
                'calcium' => 24.0,
                'phosphorus' => 12.0,
                'metabolizable_energy' => 0,
                'moisture' => 5.0,
                'ash' => 65.0,
                'status' => 'active',
            ],
            [
                'name' => 'Shell Grit',
                'description' => 'Crushed seashells or limestone grit. Provides calcium and aids in gizzard function for grinding feed. Larger particle size for layers.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 37.0,
                'phosphorus' => 0.05,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 97.0,
                'status' => 'active',
            ],
            [
                'name' => 'Dolomite',
                'description' => 'Natural source of calcium and magnesium. Contains both minerals in balanced form. Good for maintaining proper Ca:Mg ratio in feeds.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 21.0,
                'phosphorus' => 0.02,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 98.0,
                'status' => 'active',
            ],
            [
                'name' => 'Magnesium Oxide',
                'description' => 'Source of magnesium, essential for enzyme function and bone health. Required in small amounts. Helps prevent leg problems in broilers.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 99.0,
                'status' => 'active',
            ],
            [
                'name' => 'Sodium Bicarbonate',
                'description' => 'Buffering agent and source of sodium. Helps maintain proper pH in digestive system. Can improve feed efficiency and reduce heat stress.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 0.5,
                'ash' => 99.5,
                'status' => 'active',
            ],
            [
                'name' => 'Potassium Chloride',
                'description' => 'Source of potassium and chloride. Essential for electrolyte balance, nerve function, and muscle contraction. Important during heat stress.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 0.5,
                'ash' => 99.5,
                'status' => 'active',
            ],
            [
                'name' => 'Calcium Chloride',
                'description' => 'Source of calcium and chloride. Highly soluble form of calcium. Useful for rapid calcium supplementation. Can be used in liquid supplements.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 36.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 99.0,
                'status' => 'active',
            ],
            [
                'name' => 'Defluorinated Rock Phosphate',
                'description' => 'Source of phosphorus with low fluoride content. More economical than DCP/MCP but lower bioavailability. Must be defluorinated for safety.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 32.0,
                'phosphorus' => 16.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 97.0,
                'status' => 'active',
            ],
            [
                'name' => 'Gypsum (Calcium Sulfate)',
                'description' => 'Source of calcium and sulfur. Lower calcium content than limestone but provides sulfur for amino acid synthesis. Good for acid-base balance.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 23.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 98.0,
                'status' => 'active',
            ],
            [
                'name' => 'Zinc Oxide',
                'description' => 'Source of zinc, essential for enzyme function, immune system, and skin health. Important for wound healing and feather quality. Trace mineral.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 0.5,
                'ash' => 99.5,
                'status' => 'active',
            ],
            [
                'name' => 'Copper Sulfate',
                'description' => 'Source of copper, essential for iron metabolism, immune function, and feather pigmentation. Trace mineral required in small amounts.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 99.0,
                'status' => 'active',
            ],
            [
                'name' => 'Manganese Sulfate',
                'description' => 'Source of manganese, essential for bone formation, enzyme function, and eggshell quality. Important trace mineral for layers.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 99.0,
                'status' => 'active',
            ],
            [
                'name' => 'Iron Sulfate',
                'description' => 'Source of iron, essential for hemoglobin formation and oxygen transport. Prevents anemia. Trace mineral required for healthy blood.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 1.0,
                'ash' => 99.0,
                'status' => 'active',
            ],
            [
                'name' => 'Selenium Yeast',
                'description' => 'Organic source of selenium, essential antioxidant mineral. More bioavailable than inorganic selenium. Important for immune function and reproduction.',
                'unit' => 'kg',
                'crude_protein' => 15.0,
                'crude_fat' => 1.0,
                'crude_fiber' => 2.0,
                'calcium' => 0.1,
                'phosphorus' => 0.5,
                'metabolizable_energy' => 2000,
                'moisture' => 8.0,
                'ash' => 5.0,
                'status' => 'active',
            ],
            [
                'name' => 'Iodized Salt',
                'description' => 'Salt with added iodine. Provides both sodium chloride and iodine. Iodine is essential for thyroid function and metabolism regulation.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 0,
                'moisture' => 0.5,
                'ash' => 99.5,
                'status' => 'active',
            ],

            // ========== OIL & FAT SOURCES ==========
            [
                'name' => 'Palm Oil',
                'description' => 'High-energy fat source. Improves feed palatability and provides essential fatty acids. Helps reduce dust in feed. Use in cold weather for extra energy.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 100.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 8800,
                'moisture' => 0.0,
                'ash' => 0.0,
                'status' => 'active',
            ],
            [
                'name' => 'Soybean Oil',
                'description' => 'Premium vegetable oil, high in linoleic acid. Excellent energy source and improves feed texture. Better quality than palm oil but more expensive.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 100.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 8800,
                'moisture' => 0.0,
                'ash' => 0.0,
                'status' => 'active',
            ],
            [
                'name' => 'Tallow (Animal Fat)',
                'description' => 'Rendered animal fat. High-energy source, more economical than vegetable oils. Solid at room temperature. Good for pelleting.',
                'unit' => 'kg',
                'crude_protein' => 0.0,
                'crude_fat' => 99.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.0,
                'phosphorus' => 0.0,
                'metabolizable_energy' => 7700,
                'moisture' => 1.0,
                'ash' => 0.0,
                'status' => 'active',
            ],

            // ========== FIBER & BULK SOURCES ==========
            [
                'name' => 'Alfalfa Meal',
                'description' => 'High-fiber feed with good protein content. Rich in vitamins and carotenoids (for egg yolk color). Use in layer feeds for fiber and color.',
                'unit' => 'kg',
                'crude_protein' => 17.0,
                'crude_fat' => 2.5,
                'crude_fiber' => 25.0,
                'calcium' => 1.40,
                'phosphorus' => 0.25,
                'metabolizable_energy' => 1500,
                'moisture' => 10.0,
                'ash' => 8.0,
                'status' => 'active',
            ],
            [
                'name' => 'Corn Gluten Meal',
                'description' => 'By-product of corn processing. High in protein and energy. Good source of xanthophylls (for skin and egg color). Excellent for broilers.',
                'unit' => 'kg',
                'crude_protein' => 60.0,
                'crude_fat' => 2.5,
                'crude_fiber' => 2.0,
                'calcium' => 0.15,
                'phosphorus' => 0.50,
                'metabolizable_energy' => 3400,
                'moisture' => 10.0,
                'ash' => 2.0,
                'status' => 'active',
            ],
            [
                'name' => 'Brewers Dried Grains',
                'description' => 'By-product of beer production. Moderate protein and high fiber. Good source of B-vitamins. Use in limited amounts due to high fiber.',
                'unit' => 'kg',
                'crude_protein' => 26.0,
                'crude_fat' => 6.0,
                'crude_fiber' => 15.0,
                'calcium' => 0.30,
                'phosphorus' => 0.60,
                'metabolizable_energy' => 2000,
                'moisture' => 10.0,
                'ash' => 4.5,
                'status' => 'active',
            ],

            // ========== SPECIALTY INGREDIENTS ==========
            [
                'name' => 'Molasses',
                'description' => 'Liquid by-product of sugar production. Improves palatability and reduces dust. Source of energy and minerals. Use in limited amounts (max 3-5%).',
                'unit' => 'kg',
                'crude_protein' => 3.0,
                'crude_fat' => 0.0,
                'crude_fiber' => 0.0,
                'calcium' => 0.80,
                'phosphorus' => 0.10,
                'metabolizable_energy' => 2400,
                'moisture' => 25.0,
                'ash' => 8.0,
                'status' => 'active',
            ],
            [
                'name' => 'Wheat Middlings',
                'description' => 'By-product of wheat flour milling. Moderate protein and energy. Good filler ingredient. Economical option for feed formulation.',
                'unit' => 'kg',
                'crude_protein' => 16.0,
                'crude_fat' => 4.0,
                'crude_fiber' => 7.0,
                'calcium' => 0.12,
                'phosphorus' => 0.90,
                'metabolizable_energy' => 2000,
                'moisture' => 12.0,
                'ash' => 4.5,
                'status' => 'active',
            ],
            [
                'name' => 'Copra Meal (Coconut Meal)',
                'description' => 'By-product of coconut oil extraction. Moderate protein but high in fiber. Lower quality protein. Use in limited amounts in tropical regions.',
                'unit' => 'kg',
                'crude_protein' => 21.0,
                'crude_fat' => 8.0,
                'crude_fiber' => 12.0,
                'calcium' => 0.20,
                'phosphorus' => 0.60,
                'metabolizable_energy' => 2200,
                'moisture' => 10.0,
                'ash' => 5.5,
                'status' => 'active',
            ],
        ];

        foreach ($components as $component) {
            FeedComponent::firstOrCreate(
                ['name' => $component['name']],
                array_merge($component, [
                    'farm_id' => null, // System-wide components
                    'created_by' => null, // Seeded data
                ])
            );
        }

        $this->command->info('Seeded ' . count($components) . ' feed components with realistic nutritional data.');
    }
}
