@include('emails.notifications.partials.detail', ['label' => 'Task', 'value' => $task_name ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Date', 'value' => $due_date ?? ($scheduled_date ?? null)])
@include('emails.notifications.partials.detail', ['label' => 'Start time', 'value' => $start_time ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Due time', 'value' => $due_time ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Section', 'value' => $section_label ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Assigned to', 'value' => $assigned_to ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Priority', 'value' => isset($task_priority) ? ucfirst($task_priority) : ($priority_label ?? null)])
@include('emails.notifications.partials.detail', ['label' => 'Animal group', 'value' => $animal_group ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Medication', 'value' => $medication_name ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Dosage', 'value' => $dosage_instructions ?? null])
@include('emails.notifications.partials.detail', ['label' => 'Instructions', 'value' => $instructions ?? null])
